routes/route_category.py
import urllib.parse
from flask import Blueprint, jsonify, flash, abort, render_template
from utility_classes import custom_logger
from mysql_connections import mysql_view_user 
from data_classes.category import Category
from data_classes.project import Project
from data_classes.image import Image
from dataclasses import asdict
from markupsafe import escape
import urllib


 
category_routes = Blueprint('category', __name__)

@category_routes.route('<hyphen:url_category>')
def display_category_projects(url_category):
    logger = custom_logger.log("CATEGORY") #Build Logger
    logger.info(f"User visited {url_category}")
    print(url_category)

    about = "about"

    if url_category.lower() ==  about:
        flash("Welcome!", "success" )
        return render_template("about.html")

    view_user = mysql_view_user.View_User() #Build view user
    
    try:
        current_category = view_user.get_category_by_title(url_category) #Checks if the provide url category exists
    except Exception as e:
        logger.error(f"Error looking up category {url_category}: {e}")
        flash(f"An Error occurred when attempting to look up '{url_category}'", "error")
        abort(500)

    if not current_category: #if the proved url does not exist throws 404
        logger.error(f"Category '{url_category}' not found")
        flash(f"Category '{url_category}' not found", "error" )
        abort(404)

    flash("Welcome!", "success")

    
    projects = view_user.get_projects_by_category(current_category.category_id, False) #Gets list of projects per the current category

    return render_template("category.html", projects = projects, category = current_category)

routes/route_project.py
from flask import Blueprint, jsonify, flash, abort, render_template, request
from utility_classes import custom_logger
from mysql_connections import mysql_view_user
from markupsafe import escape


project_routes = Blueprint("project", __name__)


@project_routes.route("<hyphen:url_category>/<hyphen:url_project>")
def display_project_images(url_category, url_project):
    logger = custom_logger.log("PROJECT")  # Build Logger
    logger.debug(url_category)
    logger.debug(url_project)

    logger.info(f"User visited '{request.path}")

    view_user = mysql_view_user.View_User()  # Build view user

    try:
        project = view_user.get_project_by_title(url_project, url_category)
    except Exception as e:
        logger.error(f"Error looking up project {url_project}: {e}")
        flash(f"An Error occurred when attempting to look up '{url_project}'", "error")
        abort(500)

    logger.info(f"Project: {project}")
    if project is None:
        logger.error(f"Project '{url_project}' not found in category '{url_category}'.")
        flash(
            f"Project '{url_project}' not found in category '{url_category}'.", "error"
        )
        abort(404)

    images = view_user.get_project_images(project.project_id)

    current_url = request.path + "/"

    return render_template(
        "project.html", project=project, images=images, current_url=current_url
    )

templates/about.html
{% extends 'base.html' %}

{% block content %}
    <div class="about-header">
        <h2>About</h2>
        <hr>
    </div>

    <div class="about-container">
        <img class="about-image" src="https://static.wixstatic.com/media/0fee66_270710749dee4cf6b8663bd101a9bd0c~mv2.jpeg/v1/fill/w_610,h_610,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/mushroom%20hat%20profile.jpeg" Alt="Stylized self portrait">
        <div class="about-text">
            <p>Kelsey Spade is an illustrator and designer from Northern Kentucky who resides in Columbus, Ohio. She studies illustration at Columbus College of Art and Design. She likes creating illustrations for books and comics,
                as well as editorial and branding designs. Her inspirations come from fantasy and folklore, finding the magic in the mundane.
            </p>
        </div>
    </div>

    <div class="contact-header">
        <h2>Contacts</h2>
        <hr>
    </div>
    <div class="contact-container">
            <a class="contact-info" href="mailto:kelsey_spade@yahoo.com">Email</a>
            <a class="contact-info" href="https://www.instagram.com/alizakelp/">Instagram</a>
            <a class="contact-info" href="https://www.linkedin.com/in/kelsey-spade-571472267">linkedin</a>
            <a class="contact-info" href="https://www.etsy.com/shop/KelppiesCreations?ref=l2-about-shopname">Etsy</a>
            <a class="contact-info" href="https://www.youtube.com/channel/UCTNsW-D89TqSKNdoX8tqHCg">Youtube</a>
        </div>
    </div>


{% endblock %}

templates/admin.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Kelsey Spade's Portfolio Admin Dashboard</title>
        <meta name="description"
        content=
        "Admin dashboard for Kelsey portfolio website"/>
        <link rel="icon" href="https://static.wixstatic.com/media/0fee66_18f00ad0221142dfbd4c21f7e54d425f~mv2.png/v1/fill/w_549,h_289,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/Kelsey_Spade_Header.png" type="image/x-icon">

        <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='admin.css') }}">

    </head>
    <body>
        <header>
            <div class="header row">
                <a href="/">
                    <img src="https://static.wixstatic.com/media/0fee66_18f00ad0221142dfbd4c21f7e54d425f~mv2.png/v1/fill/w_549,h_289,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/Kelsey_Spade_Header.png" alt="Kelsey Spade's Butterfly-Spade Logo">
                </a>
                <h1>Admin Dashboard</h1>
                </div>
        </header>

        {% if error_message %}
            <div class="error-message">
                <h2>{{ error_message }}</h2>
                <p>Looks like something went wrong! Please click the button below to go back home or try again later</p>
                <a class= nav-button href="/">Home</a>
            </div>
        {% endif %}

        <!-- Content -->
        <div class="content">
            {% block content %}{% endblock %}
        </div>

        <script src="{{ url_for('static', filename='scripts.js') }}"></script>
        <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
    </body>
    <div class="flash-container">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="flash-message {{ category }}">{{ message }}</div>
                {% endfor %}
            {% endif %}
        {% endwith %}
    </div>
    <footer>
        <div class="footer-container">
            <p>&copy; 2025 Kelsey Spade. All Rights Reserved.</p>
            <p>Follow me on: 
                <a href="https://www.instagram.com/alizakelp/" target="_blank">Instagram</a> | 
                <a href="http://www.linkedin.com/in/kelsey-spade-571472267" target="_blank">linkedin</a> |
                <a href="https://www.etsy.com/shop/KelppiesCreations?ref=l2-about-shopname" target="_blank">Etsy</a>|
                <a href="https://www.youtube.com/channel/UCTNsW-D89TqSKNdoX8tqHCg" target="_blank">Youtube</a>
            </p>
        </div>
    </footer>
</html>

templates/admin_dashboard.html
{% extends 'admin.html' %}

{% block content %}
<div class="admin-header">
    <h2>Admin Dashboard</h2>
    <hr>
</div>

<div class="admin-container">
    <div class="admin-text">
        <p>Welcome to the admin Dashboard!
        </p>
    </div>
</div>

{% endblock %}

templates/admin_login.html
{% extends 'admin.html' %}

{% block content %}

<h1>Login</h1>

<div class="login-container">
    <form method="POST">
        <label for="username">Username</label><br>
        <input type="text" id="username" placeholder="Username goes here!" name="username" required oninvalid="this.setCustomValidity('Username is required')" oninput="this.setCustomValidity('')"><br>
        <label>Password</label><br>
        <input type="password" id="'password" placeholder="Supersecret password!" name="password" required oninvalid="this.setCustomValidity('Password is required')" oninput="this.setCustomValidity('')"><br><br>
        <button type="submit">Login</button>
    </form>
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Kelsey Spade's Portfolio</title>
        <meta name="description"
        content=
        "Hi! I'm Kelsey Spade, a soon-to-graduate student from the Columbus College of Art & Design. My portfolio showcases my love for illustration, graphic design, and comics. Check out my creative journey, featuring unique projects that mix storytelling and design. Let's connect!"/>
        <link rel="icon" href="https://static.wixstatic.com/media/0fee66_18f00ad0221142dfbd4c21f7e54d425f~mv2.png/v1/fill/w_549,h_289,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/Kelsey_Spade_Header.png" type="image/x-icon">
        <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='portfolio.css') }}">
    </head>
    <body>
        <header>
                <img src="https://static.wixstatic.com/media/0fee66_18f00ad0221142dfbd4c21f7e54d425f~mv2.png/v1/fill/w_549,h_289,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/Kelsey_Spade_Header.png" alt="Kelsey Spade's Butterfly-Spade Logo">
                <h1>Illustration and Design</h1>
                <nav>
                    {% for category in categories %}
                    <a class= nav-button href="{{ url_for('category.display_category_projects', url_category=category.category_title.lower()) }}">{{ category.category_title }}</a>
                    {% endfor %}
                </nav>
        </header>

        {% if error_message %}
            <div class="error-message">
                <h2>{{ error_message }}</h2>
                <p>Looks like something went wrong! Please click the button below to go back home or try again later</p>
                <a class= nav-button href="/">Home</a>
            </div>
        {% endif %}

        <!-- Content -->
        <div class="content">
            {% block content %}{% endblock %}
        </div>

        <script src="{{ url_for('static', filename='scripts.js') }}"></script>
        <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
    </body>
    <div class="flash-container">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="flash-message {{ category }}">{{ message }}</div>
                {% endfor %}
            {% endif %}
        {% endwith %}
    </div>
    <footer>
        <div class="footer-container">
            <p>&copy; 2025 Kelsey Spade. All Rights Reserved.</p>
            <p>Follow me on: 
                <a href="https://www.instagram.com/alizakelp/" target="_blank">Instagram</a> | 
                <a href="http://www.linkedin.com/in/kelsey-spade-571472267" target="_blank">linkedin</a> |
                <a href="https://www.etsy.com/shop/KelppiesCreations?ref=l2-about-shopname" target="_blank">Etsy</a>|
                <a href="https://www.youtube.com/channel/UCTNsW-D89TqSKNdoX8tqHCg" target="_blank">Youtube</a>
            </p>
        </div>
    </footer>
</html>

templates/category.html
{% extends 'base.html' %}

{% block content %}

<div class="category-container">
    {% for project in projects %}
        <div class="gallery">
            <a href="{{url_for('project.display_project_images', url_category=category.category_title, url_project=project.project_title) }}">
                <img class="project-image" src="{{ project.project_image.image_url }}" alt="{{ project.project_title }} image">
                <div class="project-title">{{ project.project_title }}</div>
            </a>
        </div>
    {% endfor %}
</div>
{% endblock %}

templates/image.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Kelsey Spade's Portfolio</title>
        <meta name="description"
        content=
        "Hi! I'm Kelsey Spade, a soon-to-graduate student from the Columbus College of Art & Design. My portfolio showcases my love for illustration, graphic design, and comics. Check out my creative journey, featuring unique projects that mix storytelling and design. Let's connect!"/>
        <link rel="icon" href="https://static.wixstatic.com/media/0fee66_18f00ad0221142dfbd4c21f7e54d425f~mv2.png/v1/fill/w_549,h_289,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/Kelsey_Spade_Header.png" type="image/x-icon">
        <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    </head>
    <body class="body-image">

        {% block content %}
        <div class="image-container">
            <img class="image" src="{{ image.image_url}}" alt="{{ image.image_desc }}" >
        </div>
        {% endblock %}

        <script src="{{ url_for('static', filename='scripts.js') }}"></script>
        <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
    </body>
</html>

templates/project.html
{% extends 'base.html' %}

{% block content %}
<div class="project-container">
    <div class="h3">{{project.project_title}}</div>
    {% for image in images %}
        <div class="image-card">
            <a href="{{ current_url ~ 'image_id_' ~ image.image_id|string}}">
                <img class="image" src="{{ image.image_url }}" alt="{{ image.desc }} image">
                <div class="image-title">{{ image.image_title }}</div>
            </a>
        </div>
    {% endfor %}
</div>
{% endblock %}